name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-arm64, linux-x64, win-x64]
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for ${{ matrix.platform }}
        run: |
          dotnet publish -c Release ./ChurchProjector/ChurchProjector.csproj --runtime ${{ matrix.platform }} --output ./publish/${{ matrix.platform }} /p:Version="${{ github.ref_name }}" /p:InformationalVersion="${{ github.ref_name }}" /p:FileVersion="${{ github.ref_name }}"
          find . -type f -path '*/win-x86/*' -delete
          find . -type f -path '*.pdb' -delete

      # Build the .deb package for Linux platforms only
      - name: Create .deb package for Linux
        if: startsWith(matrix.platform, 'linux')
        env:
          VERSION: ${{ github.ref_name }}
          RUNTIME: ${{ matrix.platform }}
        run: ./build/scripts/package.linux.sh

      - name: Zip ${{ matrix.platform }} artifact
        if: matrix.platform == 'win-x64'
        run: |
          cd ./publish/${{ matrix.platform }}
          zip -r ../../${{ matrix.platform }}.zip .

      # Upload the .deb package for Linux platforms
      - name: Upload .deb package artifact
        if: startsWith(matrix.platform, 'linux')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ${{ matrix.platform }}.deb

      # Upload the zip artifact for non-Linux platforms (Windows)
      - name: 'Upload Artifact'
        if: matrix.platform == 'win-x64'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ${{ matrix.platform }}.zip

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
        
    needs: build

    steps: 
      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./artifacts/**/*.zip
            ./artifacts/**/*.deb